### ISSUE TITLE
"Quit" at the end of Standard Test

### ISSUE THREAD

**Issue by MasterJH5574** [HsunGong/ppca-dht-test#11]
It seems that there isn't time to sleep while quitting.
At Line 239 in standard.go
`
	for i := 0; i < maxNodeSize; i++ {
		nodeGroup[i].Quit()
	}
`
@HsunGong

**Comment by HsunGong** [comment]
Because it is the end of this test, and the network can be crashed, the importance is to kill all service you `go-routine`, to have all `Ports` useful again.
