### ISSUE TITLE
test compilation error

### ISSUE THREAD

**Issue by jinhongyii** [HsunGong/ppca-dht-test#8]
all tests can't pass compilation.

@HsunGong

**Comment by jinhongyii** [comment]
![image](https://user-images.githubusercontent.com/44201588/61918142-f145bf00-af82-11e9-8db5-c7d5e505a8e7.png)

**Comment by MasterJH5574** [comment]
It seems that there are a lot of variables which you didn't define :(

**Comment by HsunGong** [comment]
EEE, I'll see you later, OK?
